import { DecimalPipe } from "@angular/common";

export class LiberacaoPendente{
    constructor(
        seqvoodia: string,   
        servico: string,
        dtoper: string,
        seqlinha: string,
        tipovoo: string,
        observacao: string,
        dthrausenciasrvp: string,
        partidaprev: string,   
        seqfrota: string, 
        plataforma: string,
        seqvoodiaesc: string, 
        seqtrecho: string,
        codiataorig: string,
        codiatadest: string,
        esc_partidaprev: string,
        c_apresentacao: string,
        seqfrota_plan: string,
        prefixo: string,
        seqaeronave: string,
        seqfrota_aeronave: string,
        seqtripulante: string,
        seqjornada: string,
        seqprogramacao: string,
        matricula: string,
        nome: string,
        nomeguerra: string,
        funcao: string,
        cargo: string,
        dthravisado: string,
        dthrapresentacaorealiz: string,
        tempoapresentacao: string,
        tempoapresentacaointermunic: string,
        tipolinha: string,
        seqtripulanteliberacao: string,
        seqlibaeronave: string,
        prefixo_lib: string,
        seqaeronave_lib: string,
        seqfrota_lib: string,
        codlinha: string,
        qtdtrip: string,
        dtdesligamento: string,
        chegadaprev: string,
        seqperfil: string,
        desctipovoo: string,
        codfrota: string,
        codfuncaobordo: string,
        c_partidagaragem : string,
        flgestado: string,
        c_doclinhaaeronave: string,
        nomebase: string,
    ){
  
    }
  }